### ISSUE TITLE
Errors hard to debug

### ISSUE THREAD

**Issue by stijndehaes** [cathive/concourse-chartmuseum-resource#7]
The errors in this repo are sometimes hard to debug, because of a change in chartmuseum my pipelines did not work correctly anymore. But I got the following error (first though it was because of concourse 5.0.0 upgrade).

```
Processing chart at "/tmp/build/put/git-airflow/kbc-teams/main/airflow/helm/airflow"...
Performing "helm package"...
Inspecting chart file: "/tmp/tmp-86vnnf8TfkQzC/airflow-0.0.141.tgz"...
Uploading chart file: "/tmp/tmp-86vnnf8TfkQzC/airflow-0.0.141.tgz"...
Upload of chart file has failed.


An unexpected error occured.
events.js:173
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at validChunk (_stream_writable.js:263:10)
    at Socket.Writable.write (_stream_writable.js:297:21)
    at process.on.err (/usr/local/lib/node_modules/@cathive/concourse-chartmuseum-resource/out.js:303:24)
    at process.emit (events.js:197:13)
    at processPromiseRejections (internal/process/promises.js:139:20)
    at processTicksAndRejections (internal/process/next_tick.js:82:32)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:98:12)
    at validChunk (_stream_writable.js:266:5)
    at Socket.Writable.write (_stream_writable.js:297:21)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/next_tick.js:82:32)
```

**Comment by nbob31** [comment]
I had this error when the chart parameter had an incorrect file name.
